export const PROJECT_STATUS = {
  ACTIVE: "ACTIVE",
  ARCHIVED: "ARCHIVED",
};

export const PROJECT_ROLE = {
  OWNER: "OWNER",
  EDITOR: "EDITOR",
  VIEWER: "VIEWER",
};

// ─── Artifact Types ───

export const ARTIFACT_TYPE = {
  // Research
  MARKET_ANALYSIS: "MARKET_ANALYSIS",
  COMPETITOR: "COMPETITOR",
  RESEARCH_FINDING: "RESEARCH_FINDING",
  PROBLEM_STATEMENT: "PROBLEM_STATEMENT",
  OPPORTUNITY: "OPPORTUNITY",
  HYPOTHESIS: "HYPOTHESIS",
  // Legacy (keep for backwards compatibility)
  PROBLEM_HYPOTHESIS: "PROBLEM_HYPOTHESIS",
  // Audience
  USER_PERSONA: "USER_PERSONA",
  BUYER_PERSONA: "BUYER_PERSONA",
  // Strategy
  PRODUCT_VISION: "PRODUCT_VISION",
  VALUE_PROPOSITION: "VALUE_PROPOSITION",
  POSITIONING: "POSITIONING",
  BUSINESS_MODEL: "BUSINESS_MODEL",
  KPI_OKR: "KPI_OKR",
  // Discovery & Design
  USE_CASE: "USE_CASE",
  USER_JOURNEY: "USER_JOURNEY",
  FEATURE: "FEATURE",
  EPIC: "EPIC",
  // Delivery
  USER_STORY: "USER_STORY",
  FUNCTIONAL_REQUIREMENT: "FUNCTIONAL_REQUIREMENT",
  NON_FUNCTIONAL_REQUIREMENT: "NON_FUNCTIONAL_REQUIREMENT",
  ACCEPTANCE_CRITERIA: "ACCEPTANCE_CRITERIA",
  DEPENDENCY: "DEPENDENCY",
  RISK: "RISK",
  DECISION: "DECISION",
  // Planning & Release
  ROADMAP_ITEM: "ROADMAP_ITEM",
  RELEASE: "RELEASE",
  LAUNCH_TASK: "LAUNCH_TASK",
  // Feedback & Iteration
  FEEDBACK_ITEM: "FEEDBACK_ITEM",
  ITERATION: "ITERATION",
};

export const ARTIFACT_TYPE_LABELS = {
  MARKET_ANALYSIS: "Marktanalyse",
  COMPETITOR: "Wettbewerber",
  RESEARCH_FINDING: "Research Finding",
  PROBLEM_STATEMENT: "Problem Statement",
  OPPORTUNITY: "Opportunity",
  HYPOTHESIS: "Hypothese",
  PROBLEM_HYPOTHESIS: "Problem-Hypothese",
  USER_PERSONA: "User Persona",
  BUYER_PERSONA: "Buyer Persona",
  PRODUCT_VISION: "Produktvision",
  VALUE_PROPOSITION: "Value Proposition",
  POSITIONING: "Positionierung",
  BUSINESS_MODEL: "Geschäftsmodell",
  KPI_OKR: "KPI / OKR",
  USE_CASE: "Use Case",
  USER_JOURNEY: "User Journey",
  FEATURE: "Feature",
  EPIC: "Epic",
  USER_STORY: "User Story",
  FUNCTIONAL_REQUIREMENT: "Funktionale Anforderung",
  NON_FUNCTIONAL_REQUIREMENT: "Nicht-funktionale Anforderung",
  ACCEPTANCE_CRITERIA: "Akzeptanzkriterien",
  DEPENDENCY: "Abhängigkeit",
  RISK: "Risiko",
  DECISION: "Entscheidung",
  ROADMAP_ITEM: "Roadmap Item",
  RELEASE: "Release",
  LAUNCH_TASK: "Launch Task",
  FEEDBACK_ITEM: "Feedback",
  ITERATION: "Iteration",
};

// ─── Explorer Navigator Groups ───
// Fachliche Gruppierung statt alphabetischer Reihenfolge

export const ARTIFACT_GROUPS = [
  {
    key: "research",
    label: "Research",
    types: [
      "MARKET_ANALYSIS",
      "COMPETITOR",
      "RESEARCH_FINDING",
      "PROBLEM_STATEMENT",
      "OPPORTUNITY",
      "HYPOTHESIS",
      "PROBLEM_HYPOTHESIS",
    ],
  },
  {
    key: "audience",
    label: "Audience",
    types: ["USER_PERSONA", "BUYER_PERSONA"],
  },
  {
    key: "strategy",
    label: "Strategy",
    types: [
      "PRODUCT_VISION",
      "VALUE_PROPOSITION",
      "POSITIONING",
      "BUSINESS_MODEL",
      "KPI_OKR",
    ],
  },
  {
    key: "discovery",
    label: "Discovery & Design",
    types: ["USE_CASE", "USER_JOURNEY", "FEATURE", "EPIC"],
  },
  {
    key: "delivery",
    label: "Delivery",
    types: [
      "USER_STORY",
      "FUNCTIONAL_REQUIREMENT",
      "NON_FUNCTIONAL_REQUIREMENT",
      "ACCEPTANCE_CRITERIA",
      "DEPENDENCY",
      "RISK",
      "DECISION",
    ],
  },
  {
    key: "planning",
    label: "Planning & Release",
    types: ["ROADMAP_ITEM", "RELEASE", "LAUNCH_TASK"],
  },
  {
    key: "feedback",
    label: "Feedback & Iteration",
    types: ["FEEDBACK_ITEM", "ITERATION"],
  },
];

// Flat canonical order for all types (used in progress, board, etc.)
export const ARTIFACT_TYPE_ORDER = ARTIFACT_GROUPS.flatMap((g) => g.types);

export const ARTIFACT_STATUS = {
  DRAFT: "DRAFT",
  IN_REVIEW: "IN_REVIEW",
  DONE: "DONE",
};

export const ARTIFACT_STATUS_LABELS = {
  DRAFT: "Entwurf",
  IN_REVIEW: "In Prüfung",
  DONE: "Fertig",
};

export const RELATION_TYPE = {
  DERIVES_FROM: "DERIVES_FROM",
  DEPENDS_ON: "DEPENDS_ON",
  RELATES_TO: "RELATES_TO",
  VALIDATES: "VALIDATES",
};

export const RELATION_TYPE_LABELS = {
  DERIVES_FROM: "Abgeleitet von",
  DEPENDS_ON: "Abhängig von",
  RELATES_TO: "Verknüpft mit",
  VALIDATES: "Validiert",
};

// Smart relation type suggestions: RELATION_SUGGESTIONS[sourceType][targetType] = recommended type
// Used by RelationAddDialog to auto-select the most meaningful relation type.
export const RELATION_SUGGESTIONS = {
  MARKET_ANALYSIS: {
    USER_PERSONA: "RELATES_TO", BUYER_PERSONA: "RELATES_TO",
    COMPETITOR: "RELATES_TO", OPPORTUNITY: "RELATES_TO", PROBLEM_STATEMENT: "RELATES_TO",
  },
  RESEARCH_FINDING: {
    HYPOTHESIS: "VALIDATES", PROBLEM_HYPOTHESIS: "VALIDATES",
    USER_PERSONA: "RELATES_TO", OPPORTUNITY: "RELATES_TO", PROBLEM_STATEMENT: "RELATES_TO",
  },
  PROBLEM_STATEMENT: {
    HYPOTHESIS: "DERIVES_FROM", PROBLEM_HYPOTHESIS: "DERIVES_FROM",
    OPPORTUNITY: "RELATES_TO", PRODUCT_VISION: "RELATES_TO",
  },
  OPPORTUNITY: {
    PRODUCT_VISION: "DERIVES_FROM", HYPOTHESIS: "RELATES_TO",
    FEATURE: "RELATES_TO", EPIC: "RELATES_TO",
  },
  HYPOTHESIS: {
    PRODUCT_VISION: "VALIDATES", VALUE_PROPOSITION: "RELATES_TO",
    RESEARCH_FINDING: "VALIDATES",
  },
  PROBLEM_HYPOTHESIS: {
    PRODUCT_VISION: "VALIDATES", USER_PERSONA: "RELATES_TO",
    RESEARCH_FINDING: "VALIDATES",
  },
  USER_PERSONA: {
    USE_CASE: "RELATES_TO", USER_JOURNEY: "RELATES_TO",
    USER_STORY: "RELATES_TO", VALUE_PROPOSITION: "RELATES_TO",
  },
  BUYER_PERSONA: {
    VALUE_PROPOSITION: "RELATES_TO", POSITIONING: "RELATES_TO",
  },
  PRODUCT_VISION: {
    EPIC: "DERIVES_FROM", FEATURE: "DERIVES_FROM",
    KPI_OKR: "DERIVES_FROM", ROADMAP_ITEM: "DERIVES_FROM",
  },
  VALUE_PROPOSITION: {
    PRODUCT_VISION: "DERIVES_FROM", USER_PERSONA: "RELATES_TO", FEATURE: "RELATES_TO",
  },
  POSITIONING: {
    VALUE_PROPOSITION: "DERIVES_FROM", PRODUCT_VISION: "RELATES_TO",
  },
  BUSINESS_MODEL: {
    PRODUCT_VISION: "RELATES_TO", VALUE_PROPOSITION: "RELATES_TO",
  },
  KPI_OKR: {
    PRODUCT_VISION: "DERIVES_FROM", EPIC: "VALIDATES", ROADMAP_ITEM: "VALIDATES",
  },
  EPIC: {
    USER_STORY: "DERIVES_FROM", FEATURE: "DEPENDS_ON", ROADMAP_ITEM: "RELATES_TO",
    KPI_OKR: "VALIDATES",
  },
  FEATURE: {
    EPIC: "DERIVES_FROM", USER_STORY: "DERIVES_FROM",
    FUNCTIONAL_REQUIREMENT: "DERIVES_FROM", PRODUCT_VISION: "DERIVES_FROM",
  },
  USE_CASE: {
    USER_STORY: "DERIVES_FROM", FUNCTIONAL_REQUIREMENT: "DERIVES_FROM",
    USER_PERSONA: "RELATES_TO",
  },
  USER_JOURNEY: {
    USER_STORY: "DERIVES_FROM", USE_CASE: "RELATES_TO", USER_PERSONA: "RELATES_TO",
  },
  USER_STORY: {
    FUNCTIONAL_REQUIREMENT: "DERIVES_FROM", ACCEPTANCE_CRITERIA: "VALIDATES",
    EPIC: "DERIVES_FROM", DEPENDENCY: "DEPENDS_ON",
  },
  FUNCTIONAL_REQUIREMENT: {
    NON_FUNCTIONAL_REQUIREMENT: "RELATES_TO", ACCEPTANCE_CRITERIA: "VALIDATES",
    USER_STORY: "DERIVES_FROM",
  },
  NON_FUNCTIONAL_REQUIREMENT: {
    FUNCTIONAL_REQUIREMENT: "RELATES_TO", ACCEPTANCE_CRITERIA: "VALIDATES",
  },
  ACCEPTANCE_CRITERIA: {
    USER_STORY: "VALIDATES", FUNCTIONAL_REQUIREMENT: "VALIDATES",
  },
  DEPENDENCY: {
    USER_STORY: "DEPENDS_ON", EPIC: "DEPENDS_ON", RELEASE: "DEPENDS_ON",
  },
  RISK: {
    DEPENDENCY: "RELATES_TO", EPIC: "RELATES_TO", RELEASE: "RELATES_TO",
  },
  DECISION: {
    EPIC: "RELATES_TO", FUNCTIONAL_REQUIREMENT: "RELATES_TO", RISK: "RELATES_TO",
  },
  ROADMAP_ITEM: {
    EPIC: "DEPENDS_ON", FEATURE: "DEPENDS_ON", RELEASE: "DERIVES_FROM",
  },
  RELEASE: {
    ROADMAP_ITEM: "DERIVES_FROM", LAUNCH_TASK: "DEPENDS_ON", USER_STORY: "RELATES_TO",
  },
  LAUNCH_TASK: {
    RELEASE: "DEPENDS_ON", FEATURE: "RELATES_TO",
  },
  FEEDBACK_ITEM: {
    USER_STORY: "RELATES_TO", ITERATION: "DERIVES_FROM", FEATURE: "RELATES_TO",
  },
  ITERATION: {
    FEEDBACK_ITEM: "DERIVES_FROM", EPIC: "RELATES_TO", RELEASE: "RELATES_TO",
  },
};
